#!/bin/sh

SEP=***BACKHARDDINGPACK***

for f in $(find $1 -type f); do
	file=$(basename $f)
	case $file in
		cmdline|device|mbr|model|pt|size|visuals|bootable|compresion|detected_filesystem|img|path|view|visual_filesystem|visual_mountpoint|cmosdump|postmaster|premaster|sti|ntfsclone|partclone)
			echo -n $SEP
			echo -n $f
			echo -n $SEP
			cat $f
		;;
		img.00)
			if [ -f "${f%$file}detected_filesystem" ]; then
				if [ "linux-swap" = "$(cat ${f%$file}detected_filesystem)" ]; then
					echo -n $SEP
					echo -n $f
					echo -n $SEP
					cat $f
				fi
			fi
		;;					
	esac
done