#!/bin/sh

. /lib/backharddi/definitions.sh

if [ ! -f /var/run/parted_server.pid ]; then
    [ -d /var/run ] || mkdir /var/run
    while [ ! -f /var/run/parted_server.pid ]; do
	    parted_server || true
    done
    RET=$?
    if [ $RET != 0 ]; then
        # TODO: How do we signal we couldn't start parted_server properly?
        exit $RET
    fi

    if [ -d $DEVICES ]; then
	rm -rf $DEVICES
    fi
    mkdir $DEVICES || true
    
    modprobe dm-mod
    dmraid1.0 -ay

    IFS="$NL"
    for partdev in $(parted_devices | 
	    grep -v '^/dev/md' | 
	    sed 's,^/dev/\(ide\|scsi\|[hs]d\),!/dev/\1,' | 
	    sort | 
	    sed 's,^!,,' ); do
	IFS="$TAB"
	set -- $partdev
	dirname=$(echo $1 | sed 's:/:=:g')
	dev=$DEVICES/$dirname
	mkdir $dev 
	printf "%s" "$1" >$dev/device
	printf "%s" "$2" >$dev/size
	printf "%s" "$3" >$dev/model
	
	cd $dev
	open_dialog OPEN "$(cat $dev/device)"
	read_line response
	close_dialog
	if [ "$response" = failed ]; then
	    cd /
	    rm -rf $dev
	fi
    done
fi

