#!/bin/sh

# This script sets the sataraid flag for devices that are recognized by dmraid

for dev in /var/lib/partman/devices/*; do
	[ -d "$dev" ] || continue
	cd $dev

	[ -f device ] || continue
	for frdisk in $(dmraid -s -c | grep -v "No RAID disks"); do
		case $(cat device) in
		    /dev/mapper/$frdisk)
			>sataraid
			break
			;;
		esac
	done
done
