#! /bin/sh
set +e	# ignore errors

# Make sure /dev is up to date after loading modules.

if [ -x /lib/userdevfs/update-dev ]; then
	/lib/userdevfs/update-dev
elif type udevtrigger >/dev/null 2>&1 && type udevsettle >/dev/null 2>&1; then
	udevtrigger
	udevsettle
elif type udevplug >/dev/null 2>&1; then
	udevplug
elif type udevstart >/dev/null 2>&1; then
	udevstart
elif type udevsynthesize >/dev/null 2>&1; then
	udevsynthesize
fi

exit 0
