#!/bin/sh

. /lib/backharddi/definitions.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

db_get backharddi/imagenes
imagenes="$RET"

[ -f $imagenes/${dev#$DEVICES/}/$id/img ] && printf "* " || printf "  "
