#!/bin/sh

. /usr/share/debconf/confmodule

if [ "$1" ]; then
	db_get backharddi/medio
	if [ "$RET" = cdrom -o "$RET" = net ]; then
		printf "eliminar\t"
	else
		db_metaget backharddi/text/eliminar description
		printf "eliminar\t$RET"
	fi
fi

