#!/bin/sh

. /lib/backharddi/definitions.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

db_get backharddi/imagenes
imagenes="$RET"
file="$imagenes/${dev#$DEVICES/}/$id/detected_filesystem"
visual="$imagenes/${dev#$DEVICES/}/$id/visual_filesystem"

if [ -f $file ]; then
	[ -f $visual ] && fs=$(cat $visual) || fs=$(cat $file)
	stralign -11 " $fs" #TODO: language dependent length
fi
