#!/bin/sh

dev=$1
id=$2

cd $dev

if [ -f $id/gen ]; then
	[ "$(cat $id/detected_filesystem)" = "linux-swap" ] && exit 0
	if [ -f $id/partclone ]; then
		printf "clonador\tClonar con partclone\n"
	elif [ -f $id/ntfsclone ]; then
		printf "clonador\tClonar con ntfsclone\n"
	elif [ -f $id/dd ]; then
		printf "clonador\tClonar con dd\n"
	else
		printf "clonador\tClonar con partimage\n"
	fi
fi
