#!/bin/sh

. /lib/backharddi/definitions.sh

db_get backharddi/imagenes
imagenes="$RET"

for dev in $DEVICES/*; do
	[ -d $dev ] || continue
	cd $dev
	for id in $dev/*; do
		[ -d $id ] || continue
		if [ -f $id/rest ]; then
#			open_dialog COMMIT
#			close_dialog
			count=0
			#Reintentamos volcar la tabla de particiones 5 veces
			while sfdisk -f --no-reread $(cat $imagenes/${dev##$DEVICES/}/device) < $imagenes/${dev##$DEVICES/}/pt 2>&1 | grep -q failed; do
				if [ "$count" -lt 5 ]; then
					sleep 1
					count=$((count+1))
					continue
				fi
				error 20
			done
			count=0
			while sfdisk -R $(cat $imagenes/${dev##$DEVICES/}/device) 2>&1 | grep -q busy; do
				if [ "$count" -lt 5 ]; then
					sleep 1
					count=$((count+1))
					continue
				fi
				error 20
			done
			update-dev
			[ ! -f sataraid ] || refresh_dmraid "$(cat device)"
			break
		fi
	done
done
	
stop_parted_server
