#!/bin/sh -e

. /lib/backharddi/definitions.sh

db_get backharddi/modo
[ "$RET" = rest ] || exit 0

db_get backharddi/imagenes
imagenes="$RET"

[ ! -f "$imagenes/postmaster" ] || . $imagenes/postmaster
