#!/bin/sh -e

. /lib/backharddi/definitions.sh

db_get backharddi/modo
[ "$RET" = rest ] || exit 0

db_get backharddi/imagenes
imagenes="$RET"

if [ -f "$imagenes/postmaster" ]; then
	sendstatus Conectado Ejecutando script postmaster
	. $imagenes/postmaster
fi
