#!/bin/sh -e

set -e

. /lib/backharddi/definitions.sh

dev=${1%//*}
id=${1#*//}

cd $dev

if [ -n "$id" ]; then
    open_dialog PARTITION_INFO $id
    read_line num id size type fs path name
    close_dialog
    [ "$id" ] || exit 0
    case "$fs" in
	free) ;;
	*)
	    while true; do
		set +e
		device="$(humandev $(cat device))"
		db_subst backharddi/particion_activa DEVICE "$device"
		db_subst backharddi/particion_activa PARTITION "$num"
		if [ -f  $id/detected_filesystem ]; then
		    filesystem=$(cat $id/detected_filesystem)
		    RET=''
		    db_metaget partman/filesystem_long/"$filesystem" description || RET=''
		    if [ "$RET" ]; then
			filesystem="$RET"
		    fi
		    db_subst partman/text/there_is_detected FILESYSTEM "$filesystem"
		    db_metaget backharddi/text/accion description
		    accion="$RET"
		    db_metaget partman/text/there_is_detected description
		    otherinfo="$RET"
		fi
		if [ ! -f  $id/detected_filesystem ]; then
		    db_metaget backharddi/text/no_accion description
		    accion="$RET"
		    db_metaget partman/text/none_detected description
		    otherinfo="$RET"
		fi
		db_subst backharddi/particion_activa OTHERINFO "$otherinfo"
		db_subst backharddi/particion_activa ACCION "$accion"

		ask_user /lib/backharddi/particion_activa "$dev" "$id"
		exitcode="$?"
		if [ "$exitcode" -ge 100 ]; then
		    break
		fi
		set -e
	    done
	    ;;
    esac
else
	while true; do
		set +e
		device="$(humandev $(cat device))"
		db_subst backharddi/dispositivo_activo DEVICE "$device"
	    db_metaget backharddi/text/dispositivo_accion description
	    accion="$RET"
	    db_subst backharddi/dispositivo_activo ACCION "$accion"
	    
		ask_user /lib/backharddi/dispositivo_activo "$dev"
		exitcode="$?"
		if [ "$exitcode" -ge 100 ]; then
		    break
		fi
		set -e
	done
fi
