#!/bin/sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
shift; shift; shift; shift; shift; shift; shift
name=$*

cd $dev

[ -d $id ] || mkdir $id

if [ ! -f visuals ]; then
    for i in /lib/backharddi/valid_visuals.d/*; do
	if [ -x "$i" ]; then $i; fi
    done | 
    sed 's/	.*//' | 
    grep '^backup$\|^number$\|^type$\|^size$\|^name$\|^filesystem$\|^oldfilesystem$\|^bootable$\|^method$\|^mountpoint$\|^accion$\|^compresion$' >visuals 
fi

visuals=$(cat visuals)

for v in $visuals; do
    /lib/backharddi/visual.d/$v $dev $num $id $size $type $fs $path $name
done >$id/view
