#!/bin/sh

dev=$1
id=$2

cd $dev

if [ -f $id/gen ]; then
	[ "$(cat $id/detected_filesystem)" = "linux-swap" ] && exit 0
	if [ -f $id/compresion ]; then 
		case "$(cat $id/compresion)" in
			lzo) printf "compresion\tCon compresión LZO (rápida)\n" ;;
			lzma) printf "compresion\tCon compresión LZMA (muy lenta)\n" ;;
		esac	
	else
		printf "compresion\tSin compresión\n"
	fi
fi
