#!/bin/sh

. /lib/backharddi/definitions.sh

backup=$1
auto=$3

[ $backup = none ] && exit 0

is_dir(){
	db_get backharddi/medio
	medio="$RET"
	if [ "$medio" = net ]; then
		basename $backup | grep -q ^+
		return $?
	else
		! ls "$backup"/=dev=* >/dev/null 2>&1 && ! ls "$backup"/cmosdump > /dev/null 2>&1
		return $?
	fi
}

if is_dir; then
	while true; do
		ask_user /lib/backharddi/escoge_backup $backup $auto
		exitcode="$?"
		if [ "$exitcode" -ge 100 ]; then
			break
		fi
	done	

	if [ "$exitcode" -eq 100 ]; then
		exit 100
	else
		exit 0
	fi
fi

if [ x"$auto" = xauto ]; then
       db_set backharddi/imagenes "$backup"
       exit 100
fi

if backup_ok $backup; then
	if [ -f $REST_MBR_ERROR ]; then
		db_input critical backharddi/rest_mbr_error || true
		db_go
		exit
	fi
	db_set backharddi/imagenes "$backup"
	update_metadata
	
	labels=$(find $backup -type f -name label | wc -l)
	while true; do
		if [ $labels -gt 0 ]; then
			ask_user /lib/backharddi/escoge_etiqueta $backup
		else
			ask_user /lib/backharddi/escoge_particion $backup
		fi
		exitcode="$?"
		if [ "$exitcode" -ge 100 ]; then
			break
		fi
	done	

	if [ "$exitcode" -eq 100 ]; then
		exit 100
	else
		restore_metadata
		db_reset backharddi/imagenes
		exit 0
	fi
else
	sendstatus Conectado Error
	db_input critical backharddi/no_devices || true
	db_go || exit
	db_get backharddi/no_devices
	[ "$RET" = true ] && rm -rf $backup
fi
