#!/bin/sh

. /lib/partman/definitions.sh

db_metaget backharddi/text/label description
label="$RET"
[ -z "$label" ] && label="backharddi"

no_backharddi() {
	mountpoints=$(
		/lib/partman/fstab.d/ext3 | 
		while read path mp type options dump pass; do
			echo $path,$mp
		done
	)

	for mp in $mountpoints; do
		path=${mp%,*}
		mp=${mp#*,}
		case "$mp" in
			/+_dev_*) [ "$(e2label $path)" = "$label" ] && return 0;;
			/) [ "$(e2label $path)" = "$label" ] && return 0;;
		esac
	done
    
	db_input critical backharddi/no_part || true
	db_go || true
	exit 1
}

no_backharddi
