#!/bin/sh

case "$1" in
	remove)
		;;
        purge)
                update-rc.d hwclock.sh remove >/dev/null
		update-rc.d hwclockfirst.sh remove >/dev/null
                ;;
	*)
		;;
esac

if [ -x /usr/sbin/update-mime ]; then
	update-mime
fi

