#!/bin/sh

[ -d /var/lib/partman ] || mkdir /var/lib/partman

cat /proc/modules | 
while read module_name x; do
    if [ "$module_name" = ext2 ]; then
	>/var/lib/partman/ext2
    fi
    if [ "$module_name" = vfat ]; then
	>/var/lib/partman/vfat
    fi
done

if 
    ! [ -f /var/lib/partman/ext2 ] \
    && modprobe ext2  >/dev/null 2>/dev/null
then
    >/var/lib/partman/ext2
fi

if 
    ! [ -f /var/lib/partman/vfat ] \
    && modprobe vfat  >/dev/null 2>/dev/null
then
    >/var/lib/partman/vfat
fi

if grep -q ext2 /proc/filesystems; then
    >/var/lib/partman/ext2
fi
if grep -q vfat /proc/filesystems; then
    >/var/lib/partman/vfat
fi
